#ifndef EVERLASTING_BIRTHDAY_CARD_UNDERTALE_SPIDER_DANCE_H
#define EVERLASTING_BIRTHDAY_CARD_UNDERTALE_SPIDER_DANCE_H

#include "Song.h"

extern const Song UNDERTALE_SPIDER_DANCE_SONG;


#endif //EVERLASTING_BIRTHDAY_CARD_UNDERTALE_SPIDER_DANCE_H
