#ifndef EVERLASTING_BIRTHDAY_CARD_UNDERTALE_START_MENU_H
#define EVERLASTING_BIRTHDAY_CARD_UNDERTALE_START_MENU_H

#include "Song.h"

extern const Song UNDERTALE_START_MENU_SONG;

#endif //EVERLASTING_BIRTHDAY_CARD_UNDERTALE_START_MENU_H
