#ifndef EVERLASTING_BIRTHDAY_CARD_UNDERTALE_TEM_SHOP_H
#define EVERLASTING_BIRTHDAY_CARD_UNDERTALE_TEM_SHOP_H

#include "Song.h"

extern const Song UNDERTALE_TEM_SHOP_SONG;


#endif //EVERLASTING_BIRTHDAY_CARD_UNDERTALE_TEM_SHOP_H
