#ifndef EVERLASTING_BIRTHDAY_CARD_UNDERTALE_FALLEN_DOWN_H
#define EVERLASTING_BIRTHDAY_CARD_UNDERTALE_FALLEN_DOWN_H

#include "Song.h"

extern const Song UNDERTALE_FALLEN_DOWN_SONG;

#endif //EVERLASTING_BIRTHDAY_CARD_UNDERTALE_FALLEN_DOWN_H
