#ifndef EVERLASTING_BIRTHDAY_CARD_UNDERTALE_YOUR_BEST_FRIEND_H
#define EVERLASTING_BIRTHDAY_CARD_UNDERTALE_YOUR_BEST_FRIEND_H

#include "../lib/Song/Song.h"

extern const Song UNDERTALE_YOUR_BEST_FRIEND_SONG;

#endif //EVERLASTING_BIRTHDAY_CARD_UNDERTALE_YOUR_BEST_FRIEND_H
