#ifndef EVERLASTING_BIRTHDAY_CARD_LITERALS_H
#define EVERLASTING_BIRTHDAY_CARD_LITERALS_H

#include "avr/pgmspace.h"

const char DATE_FORMAT_LITERAL[] PROGMEM = "%d.%d.%d %d:%d:%d";

#endif //EVERLASTING_BIRTHDAY_CARD_LITERALS_H
